GET {{baseUrl}}/api/v1/codes HTTP/1.1
Content-Type: application/json

###

GET {{baseUrl}}/api/v1/codes/1 HTTP/1.1
Content-Type: application/json

###

POST {{baseUrl}}/api/v1/codes HTTP/1.1
Content-Type: application/json

{
    "techStack": "C#",
    "description": "C# .Net Core 3.1",
    "duration": 100,
    "location" : "Campus"
}  

###

PUT {{baseUrl}}/api/v1/codes/12 HTTP/1.1
Content-Type: application/json  

{
    "techStack": "C#",
    "description": "C# .Net Core 3.1 (changes)",
    "duration": 10,
    "location" : "Campus"
}

###

DELETE {{baseUrl}}/api/v1/codes/12 HTTP/1.1
Content-Type: application/json